version: "3"
services: 
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"
volumes: 
  database-data:
    driver: local